export class CoresaProduct {
  SKU: string;
  CodBarra_Unitario?: string;
  CodBarra_Intermedio?: string;
  CodBarra_Master?: string;
  Descripcion?: string;
  Marca?: string;
  Macro_Familia?: string;
  Sub_Familia?: string;
  Cod_Alternativo?: string;
  Disponible?: number | string;
  Unidad_Medida?: string;
  Minimo_Venta?: boolean;
  Venta_Unitaria?: boolean;
  Precio_Lista_1?: number | string;
  Precio_Convertido?: number;
  Impuestos?: string;
  Moneda?: string;
  CantMaster?: number | string;
  CantIntermedia?: number | string;
  CantMinima?: number | string;
  Alto_cm?: number | string;
  Ancho_cm?: number | string;
  Largo_cm?: number | string;
  Dimensiones_Texto?: string;
  Peso_kg?: number | string;
  Volumen_cc?: number | string;
  Material?: string;
  Color?: string;
  Tipo_Montaje?: string;
  Tipo_Instalacion?: string;
  Soporte?: string;
  IP?: string;
  IK?: string;
  Anti_Vandalico?: string;
  Apto_Exterior?: string;
  Alimentacion?: string;
  Tension_Entrada?: string;
  Tension_Salida?: string;
  Potencia_Nominal?: string;
  Potencia_Max?: string;
  Corriente?: string;
  Polos?: string;
  Ciclos_Electricos?: string;
  Ciclos_Mecanicos?: string;
  Lumenes?: string;
  Temp_Color?: string;
  Angulo?: string;
  Dimerizable?: string;
  Tipo_Luz?: string;
  Tipo_Camara?: string;
  Tipo_Lente?: string;
  Resolucion?: string;
  Canales?: string;
  Mic?: string;
  Audio_Bidireccional?: string;
  Reconocimiento_IA?: string;
  Capacidad_Rostros?: string;
  SATA?: string;
  HDMI?: string;
  Tipo_Conexion?: string;
  Tipo_Conector?: string;
  POE?: string;
  Puertos_POE?: string;
  Ancho_Banda?: string;
  URL_Datasheet?: string;
  URL_Web?: string;
  URL_Imagen?: string;
  Certificado?: string;
}
